openapi: 3.0.0
info:
  title: Statistics Microservice API
  version: 1.0.0
  description: API for managing statistics

servers:
  - url: http://localhost:3005
    description: Development server

paths:
  /:
    get:
      summary: Get status
      responses:
        '200':
          description: Successful operation


  /lastCalledEndpoint:
    get:
      summary: Get last called endpoint
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                endpoint: "/example"
                timestamp: "2022-01-01T00:00:00.000Z"

  /mostCalled:
    get:
      summary: Get most called endpoint
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                mostCalledEndpoint:
                  endpoint: "/example"
                  count: 10
                totalCalls: 10

  /callsPerEndpoint:
    get:
      summary: Get calls per endpoint
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                callsPerEndpoint:
                  - endpoint: "/example1"
                    count: 5
                  - endpoint: "/example2"
                    count: 8
                totalEndpoints: 2

components:
  schemas:
    UserStatistics:
      type: object
      properties:
        endpoint:
          type: string
        timestamp:
          type: string
      required:
        - endpoint
        - timestamp